"""added_timing

Revision ID: 9f29f45d465b
Revises: 004
Create Date: 2025-07-29 10:28:59.175398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('timing_start', sa.Time(), nullable=True))
    op.add_column('menu_items', sa.Column('timing_end', sa.Time(), nullable=True))
    op.add_column('menu_items', sa.Column('timing_schedule', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'timing_schedule')
    op.drop_column('menu_items', 'timing_end')
    op.drop_column('menu_items', 'timing_start')
    # ### end Alembic commands ###
